### PR TITLE
	When matching id, find style elements in dom with given id

### PR DESCRIPTION
**Pull request by ajoslin**
- When id is given, look for an element with that id when getting an
  element from the in-memory cache (ideally that element is from the
  server)
- Act the same in Node and the browser
- Add options.prepend

### CODE REVIEW

**Comment by bendrucker** [comment]
Significantly expanding the functionality here doesn't feel right to me. Using `global/document` is appropriate for isolated testing and other scenarios where you want a DOM but don't care about full functionality. Even though I definitely have some sense of what the goal is here, can you explain?

**Comment by ajoslin** [comment]
You're correct, this doesn't need to run in Node. I thought i was going to do things differently at first, but globally mutating `min-document` is definitely a bad idea.

I'll amend the commit with the Node side running noops again.

Here's a bit of context for my strategy with styles:
- Insert my global styles in a tag with a special id: `insertStyles(globalStyles, {id: GLOBAL_STYLE_ID})`
- Insert my app styles in a different tag with a special id (using [stylin](https://github.com/ajoslin/stylin/blob/master/src/free-style.js#L18))

**On the server**

1) Instantiate the app at a route
2) Render the app and pull out the vtree
3) Render index.html with vdom and insert the two expected stylesheets:

``` js
    var options = {
      styles: [{
        id: insertStyles.createId(setupGlobals.STYLE_ID),
        content: setupGlobals.styles
      }, {
        id: insertStyles.createId(stylin.STYLE_ID),
        content: stylin.getCss()
      }]
    }
    var documentVtree = renderDocument(options, vtree)
```

**On the client**

Now when the client connects to the element sent from the server, insertStyles runs and gets the existing style elements.

**Comment by ajoslin** [comment]
Amended. There was a lot of functionality in there that wasn't useful. The problem was I built this and opened a PR before I was done proving out its use in my app.
- Removed server-side functionality (now noops on server like before)
- No longer add an `id` property to created styles (it's a private in-memory cache again)
- Removed options.prepend 
- Removed insertStyles.createId

The only addition now is that the library initially tries to get elements with a given ID from the document.

**Comment by bendrucker** [comment]
Nice!

**Pull request merged**
